// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchStockData(arg1:string):Promise<main.StockData>;

export function Greet(arg1:string):Promise<string>;
